name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  prepare-commit-msg:
    name: Retrive head commit message
    runs-on: ubuntu-latest
    outputs:
      HEAD_COMMIT_MSG: '${{ steps.commitMsg.outputs.HEAD_COMMIT_MSG }}'
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
      - name: find commit msg for PR
        id: commitMsg
        if: github.event_name == 'pull_request'
        run: >-
          echo "::set-output name=HEAD_COMMIT_MSG::$(git log --no-merges -1
          --oneline)"

  check-skip:
    name: Check to skip CI
    needs: prepare-commit-msg
    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(needs.prepare-commit-msg.outputs.HEAD_COMMIT_MSG, '[ci skip]')
      }}
    steps:
      - run: 'echo "${{ github.event.head_commit.message }}"'

  test:
    name: 'Node.js v${{ matrix.node }}'
    needs: check-skip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 10
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test
